version: "3.9"

services:
  db:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=travel-api-db
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    restart: on-failure
  app:
    build:
      context: .
#    ports:
#      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "/wait-for-it.sh db:27017 -- java -jar app.jar"
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
