spring:
  data:
    mongodb:
      database: "travel-api-db"
#      uri: "mongodb://user:user@localhost:27017"
      uri: "mongodb://user:user@db:27017"
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

server:
  servlet:
    context-path: "/api/v2"

cyan:
  app:
    jwtSecret: "cyan-super-long-secret-password-123"
    jwtExpirationMs: 86400000

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    url: "/api/v2/api-docs"