spring:
  data:
    mongodb:
      database: "travel-api-db"
      uri: "mongodb://user:user@localhost:27017"
      auto-index-creation: true

server:
  servlet:
    context-path: "/api/v2"

cyan:
  app:
    jwtSecret: "cyan-super-long-secret-password-123"
    jwtExpirationMs: 86400000